[theme]
base = "dark"
primaryColor = "#fdda2b"
backgroundColor = "#000000"
secondaryBackgroundColor = "#3e4342"
textColor = "#e0e0e0"
font = "sans serif"
baseFontSize = 16
baseFontWeight = 400
baseRadius = "7px"
borderColor = "#ffffff"
showWidgetBorder = true
