[theme]
base = "dark"
primaryColor = "#fe5900"
backgroundColor = "#000000"
secondaryBackgroundColor = "#151515"
textColor = "#ffffff"
font = "Chakra Petch:https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@400;500;600;700&display=swap, sans-serif"
baseFontSize = 16
baseFontWeight = 600
baseRadius = "small"
borderColor = "#434343"
showWidgetBorder = true
